### ISSUE TITLE
SMTP over TLS does not work

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/Mew#122]
This is due to #121.
I'm now trying to fix this.

**Comment by kazu-yamamoto** [comment]
@hrs-allbsd Would you check if 70d6da0 maintain your intentional behavior?

**Comment by hrs-allbsd** [comment]
> @hrs-allbsd Would you check if [70d6da0](https://github.com/kazu-yamamoto/Mew/commit/70d6da044a4f6ac8e40e489d4963b8a3d530b8a9) maintain your intentional behavior?

Yes, thanks for fixing it.  My patch did not honor the assumption that (mew-serv-to-port) always resolved the service name to a number before entering into (mew-open-network-stream).  The (stringp port) check was needed before (string-match) as in your change.

**Comment by kazu-yamamoto** [comment]
Thanks. Let's close this.
