### ISSUE TITLE
"Invalid function" when byte-compiled on Emacs 28?

### ISSUE THREAD

**Issue by tdanckaert** [kazu-yamamoto/Mew#155]
Hello,

I recently upgraded to emacs 28 (now 28.2, but the problem also appeared on emacs 28.1), and emacs raises a lot of "Invalid function" errors for macros such as `mew-called-interactively-p` or `mew-summary-with-mewl` (just to give 2 examples, I think there are more).

The errors go away if I remove byte-compiled .elc files from the mew installation directory.

I wonder if the problem is related to recently introduced native compilation?  I've tried disabling native compilation by setting `native-comp-deferred-compilation` to `nil`, but that didn't seem to have an effect.

**Comment by kazu-yamamoto** [comment]
I'm using Emacs 28.1. But byte-compile is fine and I don't encounter such errors.
Are you sure that you byte-compile the el files with Emacs 28.2?

**Comment by tdanckaert** [comment]
Yes, I byte-compile with the same version.  I did a few more tests and I'm now quite sure it's related to the native compilation.  The problem also disappears when I disable native compilation during byte compilation as well as when running the code, by adding the following to early-init.el:
```
(setq native-comp-deferred-compilation nil)
      native-comp-speed -1)
```

Do you have native compilation enabled on your version on emacs?

**Comment by kazu-yamamoto** [comment]
The native compilation is disabled.

**Comment by tdanckaert** [comment]
I believe the problem maybe caused by the fact that native compilation is done asynchronously.  The order in which files get compiled may differ, and this may cause some macros (such as `mew-called-interactively-p`) to be defined too late.  I managed to improve things by adding some `(eval-when-compile (require 'mew-env.el))` in various modules, but some of those led to circular requires...  I'll submit a pull request when I manage to fix it?

**Comment by kazu-yamamoto** [comment]
If you send a PR, I'm willing to review it.
