### ISSUE TITLE
`Subject:` string gets doubled in reply

### ISSUE THREAD

**Issue by lemzwerg** [kazu-yamamoto/Mew#161]
[mew 7ab02416029d0f15580efa3c4c3ff39f32d7c0ad]
[GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu,
 GTK+ Version 3.24.34, cairo version 1.16.0) of 2023-02-01]

Please consider the attached e-mail, generated by Thunderbird 102.6.0.  If I reply to that by pressing 'R', the subject fields gets doubled and looks like this:

```
Subject: Re: Tie not working as expected,Re: Tie not working as expected
```

It's very easy to miss that, not manually correcting it – I already got complaints.

It seems to me that Mew has difficulties with OpenPGP/MIME signed messages.  Maybe the simplest solution is to accept a single 'Subject' field only (namely the first)?

[problematic-email.txt](https://github.com/kazu-yamamoto/Mew/files/10555757/problematic-email.txt)

**Comment by svenha** [comment]
Thanks for opening the issue. I also hate to edit all these subject lines :-) BTW: a related issue is #114, at least the point 2.

**Comment by kazu-yamamoto** [comment]
The message has two To: field. So, this message is broken. Should we work around with this illegal case?

**Comment by lemzwerg** [comment]
I have no idea about the well-formedness of such e-mails, sorry.  I only know that they are created by Mozilla, then distributed via Mailman 2.1.29 as used for mailing lists on gnu.org, so I vote for yes – it's apparently only the Mew e-mail reader that chokes; at least nobody else reported similar issues on the list.

**Comment by svenha** [comment]
The problematic mails that I get are all from Thuderbird with gpg support. The header lines `To:` `From:` `Subject:`  `Reply-To:` come twice (non-adjacent). Other mailers just show one of them.

**Comment by svenha** [comment]
Thanks @kazu-yamamoto. Answering with 'a' has now a correct subject header, too.
