### ISSUE TITLE
Releasing Mew v6.9

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/Mew#164]
@tats I'm going to release Mew v6.9. To view files nicely on github, many files were moved into sub-directories. I believe that all documents are updated. It would be appreciated if you did final check.

**Comment by kazu-yamamoto** [comment]
`make archive` makes a tar ball. Since I have not put a new version tag, its file name includes the previous version.

**Comment by tats** [comment]
* RELEASENOTE.md:

You may remove the "Important note" section, seems not so important.
Please consider adding "* Supporting unix domain socket." to the Differences.

* bin/incm.c:
* bin/mewencode.c:
* bin/mewl.c:

Typo, 20130210 -> 20230210

* LICENSE:
* LICENSE.ja:
* elisp/mew.el:

Please consider updating copyright years -2015 to -2023.

* elisp/mew-demo.el:
* info/mew.texi:

Please consider updating copyright years -2018 to -2023.

* info/mew.texi:

Emacs 24.3 -> Emacs 26.1

* info/mew.info:
* info/mew.ja.info:

Itemizing seems broken.  Use Emacs 26 or the makeinfo command as workaround.

**Comment by kazu-yamamoto** [comment]
Thanks. I will work for these.

> Itemizing seems broken. Use Emacs 26 or the makeinfo command as workaround.

What do you mean?

It seems to me that Emacs 27 requires a empty line after each `@item`. So, I changed `mew.texi`. Is `mew.info` still broken?

**Comment by tats** [comment]
Yes, still broken.  Look carefully.

info/mew.info:
```
>  - You can easily search messages with keywords etc.ew automatically decodes me
> ssages encrypted with PGP orS/MIME. It also automatically verifies signed messa
> ges.
> 
>  - You can easily encrypt or sign a message with PGP or S/MIME.t takes a bit of
>  time to analyze MIME syntax or to verify aPGP or S/MIME signature. While the u
> ser is reading a message, Mew
>      processes the next message so that the next message can be
>      displayed faster. Analyzed messages are cached briefly.
> 
>  - You can view multiple folders simultaneously.election/Thread, a mechanism to
>  display the flow ofmessages, is supported. You can make Selection from message
> s
>      matched to a keyword and make Thread from the Selection.
```

**Comment by kazu-yamamoto** [comment]
OK. I understand. I will revert c83c954 and use Emacs 26.3. (sigh)

**Comment by tats** [comment]
* mew.texi:
> シンボルに何があるのかは、"dot.mew" を見て下さい。
> To know what kind of symbols are prepared, see the "dot.mew".

dot.mew -> conf/dot.theme

**Comment by tats** [comment]
* mew.texi:
> 色を変更するには、Mew のソースと一緒に配布されている "dot.theme" を
> To modify colors, copy "dot.theme" contained Mew's source file to

dot.theme -> conf/dot.theme

**Comment by kazu-yamamoto** [comment]
Copied from the previous messages.

* RELEASENOTE.md:

You may remove the "Important note" section, seems not so important.
Please consider adding "* Supporting unix domain socket." to the Differences.

* bin/incm.c:
* bin/mewencode.c:
* bin/mewl.c:

Typo, 20130210 -> 20230210

* LICENSE:
* LICENSE.ja:
* elisp/mew.el:

Please consider updating copyright years -2015 to -2023.

* elisp/mew-demo.el:
* info/mew.texi:

Please consider updating copyright years -2018 to -2023.

* [ ] info/mew.texi:

Emacs 24.3 -> Emacs 26.1

* [ ] info/mew.info:
* [ ] info/mew.ja.info:

Itemizing seems broken.  Use Emacs 26 or the makeinfo command as workaround.

**Comment by tats** [comment]
> dot.mew -> conf/dot.mew

In mew.texi, it should be conf/dot.theme.

```
シンボル @samp{header-subject} は、ヘッダの "Subject:" の値を意味してい
The symbol @samp{header-subject} means the value of the "Subject:"

シンボルに何があるのかは、"dot.mew" を見て下さい。
To know what kind of symbols are prepared, see the "dot.mew".
```
