### ISSUE TITLE
`make elisp` fails with "Error: Symbol’s function definition is void: mew-match-string"

### ISSUE THREAD

**Issue by yasuhirokimura** [kazu-yamamoto/Mew#180]
After commit cf354e4 is merged to master branch, `make elisp` fails with error messages as below.

> Error: Symbol’s function definition is void: mew-match-string

I confirmed it with following two environments.

OS: FreeBSD 13.1-RELEASE amd64
Emacs: commit 0330cff65ae of upstream master branch

OS: 64bit Windows 10 22H2
Emacs: commit 95d5154feed of upstream master branch

**Comment by tats** [comment]
Oops, sorry.  Replacing mew-match-string with match-string may prevent the issue.
