### ISSUE TITLE
global-mode-string can indeed be a string, not a list

### ISSUE THREAD

**Issue by tkurtbond** [kazu-yamamoto/Mew#183]
Unfortunately, the function mew-biff-setup in mew-net.el assumes `global-mode-string`  is always a lisp.  But there is an easy fix: check to see if it is string, and if it is, set `global-mode-string ` to be a new list that contains the old string value of `global-mode-string `.

Here's a patch.
[mew.patch](https://github.com/kazu-yamamoto/Mew/files/11081581/mew.patch)

**Comment by kazu-yamamoto** [comment]
This patch seems good. Could you send a pull request so that we can record your credit?
