### ISSUE TITLE
incorrect keys in encryption

### ISSUE THREAD

**Issue by tats** [kazu-yamamoto/Mew#77]
When the following keys are imported,

  - 1024D/97AA33D6 Dima Barsky <dima@debian.org>
  - 1024D/1A944AD7 Martin Albert <ma@debian.org>

I write a mail with `To: ma@debian.org`, and encrypt it,
then it is encrypted with Dima's key instead of Martin's key.

Is it a known issue?  Should the `decrypters` be around with "<"
and ">" in `mew-pgp-encrypt`, `mew-old-pgp-encrypt` and so on?
Comments?

**Comment by tats** [comment]
> decrypters be around with `"<"` and `">"`

Patch available at https://github.com/kazu-yamamoto/Mew/pull/78

**Comment by kazu-yamamoto** [comment]
Closing thanks to #78.
