### ISSUE TITLE
Functional bug with GPG 2.1.4

### ISSUE THREAD

**Issue by sheepduke** [kazu-yamamoto/Mew#81]
Hi,

I've been using Mew for almost two years, but Now I found a functional bug when using Mew with GPG 2.1.4, i.e. "Master password is wrong".

Because it's not actually a bug, so it cannot be backtraced.
That happens when `mew-passwd-load` or `mew-passwd-save` tries to start-process, but process filter cannot get any result from GPG, so Mew would not prompt user for input password. Therefore, master password is never set.

The reason is, from GnuPG 2.1, it uses pinentry as its agent program.

The agent program does two things which cause the problem:
- Accept user input via graphic message box or cursor-based input box.
  GPG will not output anything to starndard output.
- Cache the master password for some time.
  GPG will directly use cached password without any prompt, only below:
  gpg: AES encrypted data
  gpg: encrypted with 1 passphrase

Both makes `mew-passwd-filter` has no chance to prompt the user, so Mew can't get any master password from user, `mew-passwd-master` is nil.
Then, when `mew-passwd-save` or `mew-passwd-load` is called, it will say "Master password is wrong".

Possible solution:
- For GPG agent:
  GnuPG provides one option named `--pinentry-mode` which can be set to `loopback`  to force GnuPG use stdout and prompt password traditionally.
  One configure must be enabled in `~/.gnupg/gpg-agent.conf`, with line below:
  `allow-loopback-pinentry`
  Also, when Mew `start-process`, it must provide option `--pinentry-mode` with
  value `loopback`.
  After doing this, Mew is able to get output from GPG.
- For password cache:
  GPG will output following two lines when using cached password:

```
gpg: AES encrypted data
gpg: encrypted with 1 passphrase
```

Inside `mew-passwd-filter', capture this situation and prompt for
master password if nil.

Talk is cheap, here's the code works for me:
(last two could be a little bit ugly... ;-)
- Inside `mew-passwd-filter', within the`cond' clause:

```
((string-match "encrypted with" string)
 (unless mew-passwd-master
   (mew-passwd-read-passwd "Master password: ")))
```
- Function for get the version of GPG.

```
(defun mew-passwd-check-gpg-version ()
  (let ((version (shell-command-to-string "gpg --version")))
    (setq version (substring version 0 (string-match (string ?\n) version)))
    (string-to-number (substring version (string-match "[1-9]" version)))))
```
- Inside `mew-passwd-save', when starting process.

```
    (setq pro (mew-start-process-lang
           mew-passwd-encryption-name (current-buffer) mew-prog-passwd
           (when (>= (mew-passwd-check-gpg-version) 2.1)
              "--pinentry-mode")
           (when (>= (mew-passwd-check-gpg-version) 2.1)
              "loopback")
       "-c" "--cipher-algo" mew-passwd-cipher
       "--yes" "--output" file tfile))
```
- Like 3, but in `mew-passwd-load'.

I hope it does make sense somehow.

Best wishes,
Danny

**Comment by kazu-yamamoto** [comment]
Thank you for this report. Would you give me a pull request which implements the second solution? I think that the result of `(>= (mew-passwd-check-gpg-version) 2.1)` should be stored in a local variable to avoid calling gnupg twice.
