### ISSUE TITLE
Reduce diffs among mew-darwin.el, mew-unix.el, and mew-win32.el

### ISSUE THREAD

**Issue by mernst** [kazu-yamamoto/Mew#90]
Files mew-darwin.el, mew-unix.el, and mew-win32.el serve similar purposes, but it is difficult to understand how they differ, and the diffs between them are large and unweildy.  Many of the differences could be eliminated by reordering some sections in the files and using a uniform style.

For example, mew-unix.el has sections in this order:

;;;
;;; Text/Html, Application/Xml
;;;

;;;
;;; Image
;;;

;;;
;;; MIME setting
;;;

By contrast, mew-darwin.el has sections in this order:

;;
;; MIME setting
;;

;;;
;;; Text/Html, Application/Xml, Image
;;;

Using the same order and number of sections would make the similarities and differences among the files more apparent, and it might enable refactoring some common code out of all three files.

**Comment by kazu-yamamoto** [comment]
You can change the code as you like and please send me a pull request.

**Comment by mernst** [comment]
Could you take a look at the pull request I submitted last year?
